### ISSUE TITLE
Log file missing in v86

### ISSUE THREAD

**Issue by adamjohnwright** [reactome/SBMLExporter#8]
The Jenkins file is expecting a log file in the archive step. This release the archive step errored because it couldn't find the log file. I think this was probably caused by an update of the dependencies.

**Comment by cqgong** [comment]
> The Jenkins file is expecting a log file in the archive step. This release the archive step errored because it couldn't find the log file. I think this was probably caused by an update of the dependencies.

Hi Adam, I've fixed it and there should be a log file now when executing jar file.
